minetest.register_alias("custom:glass_fragments","vessels:glass_fragments")
minetest.register_alias("custom:vessels_shelf","vessels:shelf")
minetest.register_alias("custom:steel_bottle","vessels:steel_bottle")
minetest.register_alias("custom:glass_bottle","vessels:glass_bottle")
minetest.register_alias("custom:drinking_glass","vessels:drinking_glass")
