gameid = Cashs_World
creative_mode = false
enable_damage = true
loadmod carts = true
loadmod protector = true
loadmod xban2 = false
loadmod WorldEdit = false
loadmod hud_hunger = false
loadmod moonrealm = false
loadmod unified_inventory = false
loadmod inventory_plus = true
loadmod zcg = true
loadmod u_skinsdb = false
loadmod wardrobe = true
loadmod city_block = false
backend = redis
redis_address = 127.0.0.1
redis_port = 30010
redis_hash = IGNORED
player_backend = files
